language: python
install:
    - pip install tox
script:
    - tox
env:
    matrix:
        - TOXENV=py36-sqlite
notifications:
    email:
        recipients:
            - developers@nan-tic.com
        on_success: change
        on_failure: always
